person:
    dog:
        name: haha${random.int,100}
        age: 16
    list:
        - 10
        - 20
        - ${person.dog.name:hello}
        - ${person.dog.address:hello}
    map: {k1: 1, k2: 12}
logging:
   level:
      root: error
---
spring:   profiles: devperson:
    dog:
        name: ss
        age: 1
    list:
        - 10
        - 20
        - ${person.dog.name:hello}
        - ${person.dog.address:hello}
    map: {k1: 1, k2: 12}
